edition = "2021"
trailing_comma = "Never"
imports_granularity = "Module"
imports_layout = "HorizontalVertical"
wrap_comments = true
reorder_impl_items = true
use_field_init_shorthand = true
condense_wildcard_suffixes = true
format_code_in_doc_comments = true
format_strings = true
struct_lit_single_line = false
single_line_if_else_max_width = 0
chain_width = 40
tab_spaces = 2
max_width = 80
